apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: dp1t2cfox-java-quarkus
  janus-idp.io/tekton: dp1t2cfox-java-quarkus
  backstage.io/kubernetes-id: dp1t2cfox-java-quarkus
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: dp1t2cfox-java-quarkus
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
